"""Generate static public listing. No resumes or applicant personal data."""
import csv, json, html
from pathlib import Path
root=Path(__file__).resolve().parents[1]
site=root/'site';site.mkdir(exist_ok=True)
p=root/'vagas_para_revisar.csv'
with p.open(encoding='utf-8-sig',newline='') as f: rows=list(csv.DictReader(f))
public=[{k:r.get(k,'') for k in ('empresa','titulo','nivel','local','modalidade','area','pontuacao','url')} for r in rows]
(site/'vagas.json').write_text(json.dumps(public,ensure_ascii=False,indent=2),encoding='utf-8')
(site/'index.html').write_text('''<!doctype html><html lang="pt-BR"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>JobHunter AI | Vagas</title><style>body{font:16px system-ui;max-width:1000px;margin:2rem auto;padding:0 1rem;background:#f7f8fa;color:#1a2430}header{margin-bottom:2rem}.card{background:white;border:1px solid #ddd;border-radius:12px;padding:1rem;margin:1rem 0}a{color:#0757b5}input,select{padding:.7rem;border:1px solid #bbb;border-radius:8px;max-width:100%}.controls{display:flex;gap:1rem;flex-wrap:wrap}small{color:#555}</style><header><h1>JobHunter AI</h1><p>Vagas de estágio e júnior · São Paulo, região metropolitana e remoto</p><small>Consulta pública; não realiza candidaturas. Confirme elegibilidade e disponibilidade no site oficial.</small></header><div class="controls"><input id="q" placeholder="Buscar por título ou empresa" aria-label="Pesquisar"><select id="area" aria-label="Área"><option value="">Todas as áreas</option></select></div><p id="count" aria-live="polite"></p><main id="jobs"></main><script>
let all=[];const q=document.querySelector('#q'),area=document.querySelector('#area'),jobs=document.querySelector('#jobs');function render(){let term=q.value.toLowerCase(),a=area.value;let items=all.filter(x=>(!a||x.area===a)&&(`${x.titulo} ${x.empresa} ${x.local}`.toLowerCase().includes(term)));document.querySelector('#count').textContent=items.length+' vagas';jobs.replaceChildren();for(const x of items){const d=document.createElement('article');d.className='card';const h=document.createElement('h2');h.textContent=x.titulo;const p=document.createElement('p');p.textContent=`${x.empresa} · ${x.local} · ${x.nivel} · ${x.area}`;const link=document.createElement('a');link.href=x.url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='Abrir vaga oficial';d.append(h,p,link);jobs.append(d)}}fetch('vagas.json').then(r=>r.json()).then(data=>{all=data;for(const a of [...new Set(all.map(x=>x.area))].sort()){let o=document.createElement('option');o.value=a;o.textContent=a;area.append(o)}render()}).catch(()=>document.querySelector('#count').textContent='Não foi possível carregar as vagas');q.addEventListener('input',render);area.addEventListener('change',render)
</script></html>''',encoding='utf-8')
print('Site gerado com',len(public),'vagas públicas')
